# --------------------------------------------------------------------------
# HuntPass Settings
# --------------------------------------------------------------------------
EnabledHuntPass = True

# Period to end.
# Retail 1 month.
DayOfMonth = 16

# Pass Premium Cost.
# Retail is 3600 L-Coin.
# IKARUS: ativado com o item do Hunt Pass (72289 = Hunt Pass Additional Reward Ticket), 1 unidade.
PremiumItemId = 72289
PremiumItemCount = 1

# Please take caution when changing anything.
# Required Points per Window or step.
PointsForStep = 2400
